# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: pretty-format-json
        args: [--autofix, --indent=4]
      - id: forbid-submodules
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 35.46.1
    hooks:
      - id: renovate-config-validator
  - hooks:
      - id: black
    repo: https://github.com/psf/black
    rev: 23.3.0
  - hooks:
      - entry: poetry run mypy
        files: src
        id: mypy
        language: system
        name: typing checks
        types: [python]
    repo: local
  - hooks:
      - id: ruff
    repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.261
  - hooks:
      - id: yamlfmt
    repo: https://github.com/google/yamlfmt
    rev: v0.9.0
